"""Technology catalog used by RAG-PARSE B-206 stack detection.

The catalog gives deterministic coverage for common manifests first. When a
dependency is outside this table, manifest.py can ask the LLM to classify it
using the same category guide.
"""

from __future__ import annotations

CATEGORY_GUIDE = {
    "language": "Programming language or language-level toolchain.",
    "runtime": "Runtime or execution environment.",
    "framework": "Application, frontend, backend, or mobile framework.",
    "database": "Database, cache, search engine, or datastore.",
    "orm": "ORM, database mapper, or query abstraction.",
    "infra": "Container, orchestration, CI/CD, cloud, or deployment infrastructure.",
    "server": "Application server, ASGI/WSGI server, or web server.",
    "library": "General-purpose library or SDK.",
    "ai": "LLM, RAG, ML/AI, embedding, or agent framework.",
    "ml": "Machine learning or deep learning framework.",
    "test": "Testing, linting, or QA tool.",
    "build": "Build tool, bundler, or package manager.",
    "extension": "Database/application extension or plugin.",
}

TECH_CATEGORY = {
    # Languages / runtimes
    "JavaScript": "language",
    "TypeScript": "language",
    "Python": "language",
    "Dart": "language",
    "Go": "language",
    "Rust": "language",
    "Java": "language",
    "Kotlin": "language",
    "Ruby": "language",
    "PHP": "language",
    "C#": "language",
    "Node.js": "runtime",
    "Bun": "runtime",
    "Deno": "runtime",
    # JS / frontend / mobile
    "Next.js": "framework",
    "React": "framework",
    "Vue": "framework",
    "Angular": "framework",
    "Svelte": "framework",
    "Nuxt": "framework",
    "Express": "framework",
    "NestJS": "framework",
    "Fastify": "framework",
    "Vite": "build",
    "Webpack": "build",
    "Tailwind CSS": "library",
    "Prisma": "orm",
    "Flutter": "framework",
    "React Native": "framework",
    # Python backend / data / AI
    "FastAPI": "framework",
    "Django": "framework",
    "Flask": "framework",
    "Starlette": "framework",
    "Uvicorn": "server",
    "Gunicorn": "server",
    "SQLAlchemy": "orm",
    "Pydantic": "library",
    "LangChain": "ai",
    "LlamaIndex": "ai",
    "OpenAI SDK": "ai",
    "pandas": "library",
    "NumPy": "library",
    "PyTorch": "ml",
    "TensorFlow": "ml",
    "scikit-learn": "ml",
    # JVM / other backend
    "Spring Boot": "framework",
    "Maven": "build",
    "Gradle": "build",
    "Rails": "framework",
    "Laravel": "framework",
    ".NET": "framework",
    # Datastores
    "PostgreSQL": "database",
    "MySQL": "database",
    "MongoDB": "database",
    "Redis": "database",
    "SQLite": "database",
    "Elasticsearch": "database",
    "OpenSearch": "database",
    "pgvector": "extension",
    # Infra
    "Docker": "infra",
    "Docker Compose": "infra",
    "Kubernetes": "infra",
}

NODE_DEP_TO_TECH = {
    "next": "Next.js",
    "react": "React",
    "vue": "Vue",
    "@angular/core": "Angular",
    "svelte": "Svelte",
    "nuxt": "Nuxt",
    "express": "Express",
    "@nestjs/core": "NestJS",
    "fastify": "Fastify",
    "typescript": "TypeScript",
    "vite": "Vite",
    "webpack": "Webpack",
    "tailwindcss": "Tailwind CSS",
    "prisma": "Prisma",
    "react-native": "React Native",
    "openai": "OpenAI SDK",
    "langchain": "LangChain",
}

PY_DEP_TO_TECH = {
    "fastapi": "FastAPI",
    "django": "Django",
    "flask": "Flask",
    "starlette": "Starlette",
    "uvicorn": "Uvicorn",
    "gunicorn": "Gunicorn",
    "sqlalchemy": "SQLAlchemy",
    "pydantic": "Pydantic",
    "langchain": "LangChain",
    "llama-index": "LlamaIndex",
    "llama_index": "LlamaIndex",
    "openai": "OpenAI SDK",
    "pandas": "pandas",
    "numpy": "NumPy",
    "torch": "PyTorch",
    "tensorflow": "TensorFlow",
    "scikit-learn": "scikit-learn",
    "sklearn": "scikit-learn",
    # DB drivers -> DB presence only; driver version is not DB server version.
    "asyncpg": "PostgreSQL",
    "psycopg": "PostgreSQL",
    "psycopg2": "PostgreSQL",
    "pymysql": "MySQL",
    "mysqlclient": "MySQL",
    "pymongo": "MongoDB",
    "redis": "Redis",
}

PY_DB_DRIVER_PKGS = {
    "asyncpg",
    "psycopg",
    "psycopg2",
    "pymysql",
    "mysqlclient",
    "pymongo",
    "redis",
}

MANIFEST_TECHS = {
    "package.json": (("Node.js", None), ("JavaScript", None)),
    "tsconfig.json": (("TypeScript", None),),
    "bun.lock": (("Bun", None),),
    "bun.lockb": (("Bun", None),),
    "deno.json": (("Deno", None),),
    "deno.jsonc": (("Deno", None),),
    "requirements.txt": (("Python", None),),
    "pyproject.toml": (("Python", None),),
    "go.mod": (("Go", None),),
    "cargo.toml": (("Rust", None),),
    "pom.xml": (("Java", None), ("Maven", None)),
    "build.gradle": (("Java", None), ("Gradle", None)),
    "build.gradle.kts": (("Kotlin", None), ("Gradle", None)),
    "gemfile": (("Ruby", None),),
    "composer.json": (("PHP", None),),
    "pubspec.yaml": (("Dart", None),),
    "pubspec.yml": (("Dart", None),),
}

COMPOSE_IMAGE_TO_TECH = {
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "mariadb": "MySQL",
    "mongo": "MongoDB",
    "mongodb": "MongoDB",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "opensearch": "OpenSearch",
}

DOCKER_IMAGE_TO_TECH = {
    "python": "Python",
    "node": "Node.js",
    "nodejs": "Node.js",
    "golang": "Go",
    "go": "Go",
    "rust": "Rust",
    "openjdk": "Java",
    "eclipse-temurin": "Java",
    "maven": "Maven",
    "gradle": "Gradle",
    "ruby": "Ruby",
    "php": "PHP",
    "composer": "PHP",
    "dotnet": ".NET",
    "aspnet": ".NET",
    "sdk": ".NET",
}
